<?php include ('header.phtml'); ?>

<form method="POST" action="index.php">
	Filtrer par utilisateur : 
	<select name="user">
		<option value="-1">All</option>
		<?php foreach ($dataUsers as $user) { ?>
			<option value="<?php echo $user['id']; ?>"><?php echo $user['nickname']; ?></option>
		<?php } ?>
	</select>
	<input type="submit" name="filter" value="Filtrer" />
</form>

<ul>
	<?php foreach ($dataTasks as $task) { ?>
		<li>
			<input id="status_<?php echo $task['id']; ?>" type="checkbox" <?php if ($task['status'] == 1) { echo "checked"; } ?>/><label for="status_<?php echo $task['id']; ?>"><?php echo $task['task']; ?></label>
		</li>				
	<?php } ?>
</ul>

<form method="POST" action="index.php">
	<label for="_task">Ajouter une tache : </label>
	<textarea id="_task" name="task"></textarea> 
	<select name="user_id">
		<?php foreach ($dataUsers as $user) { ?>
			<option value="<?php echo $user['id']; ?>"><?php echo $user['nickname']; ?></option>
		<?php } ?>
	</select>
	<input type="submit" name="addTask" value="Ajouter" />
</form>

<?php include ('footer.phtml'); ?>
